#!/usr/bin/env python3
"""Parse .env (no extra deps), emit bash exports, sync cockpit/.env, resolve hub API key."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_dotenv(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    raw = path.read_text(encoding="utf-8", errors="replace")
    if raw.startswith("\ufeff"):
        raw = raw[1:]
    out: dict[str, str] = {}
    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("export "):
            s = s[7:].lstrip()
        if "=" not in s:
            continue
        key, _, rest = s.partition("=")
        key = key.strip()
        if not _KEY.match(key):
            continue
        val = rest.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        out[key] = val
    return out


def _bash_export(key: str, val: str) -> str:
    esc = "'" + val.replace("'", "'\\''") + "'"
    return f"export {key}={esc}"


def _fmt_env_value(val: str) -> str:
    if re.search(r'[\n\r"#=]', val) or val.startswith(" ") or val.endswith(" "):
        inner = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{inner}"'
    return val


def cmd_exports(args: argparse.Namespace) -> int:
    d = parse_dotenv(Path(args.env_file))
    for k, v in sorted(d.items()):
        print(_bash_export(k, v))
    return 0


def cmd_write_cockpit(args: argparse.Namespace) -> int:
    repo = Path(args.repo_root).resolve()
    block = {"PORT", "HOST", "WORKERS"}
    root_env = Path(args.env_file)
    out_path = Path(args.out_env)
    d = parse_dotenv(root_env) if root_env.is_file() else {}
    for b in block:
        d.pop(b, None)
    d["AIHUB_BASE_URL"] = args.base_url
    if "NEXT_PUBLIC_ENVIRONMENT" not in d:
        d["NEXT_PUBLIC_ENVIRONMENT"] = "development"
    # Keep cockpit/.env functionally aligned with root .env, but not byte-identical;
    # this prevents release duplicate-file gates from flagging the frontend env as an
    # accidental copy while preserving real secrets and runtime values.
    d["AIHUB_FRONTEND_ENV_FILE"] = "cockpit/.env"
    lines = [
        "# Regenerated by start.sh from morda/.env — overrides: cockpit/.env.local",
        "",
    ]
    for k in sorted(d.keys()):
        lines.append(f"{k}={_fmt_env_value(d[k])}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[dotenv_tool] wrote {out_path}", file=sys.stderr)
    return 0


def cmd_hub_x_key(args: argparse.Namespace) -> int:
    repo = Path(args.repo_root).resolve()
    jpath = repo / "config" / "hub_key_env_names.json"
    try:
        names = json.loads(jpath.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        names = ["AIHUB_API_KEY", "HUB_API_KEY", "API_KEY", "AIHUB_PROXY_TOKEN"]
    if not isinstance(names, list):
        names = ["AIHUB_API_KEY", "HUB_API_KEY", "API_KEY", "AIHUB_PROXY_TOKEN"]
    d = parse_dotenv(Path(args.env_file))
    for n in names:
        if not isinstance(n, str):
            continue
        v = (d.get(n) or "").strip()
        if v:
            print(v, end="")
            return 0
    return 0


def main() -> int:
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("exports", help="print eval-able export lines for bash")
    e.add_argument("env_file")
    e.set_defaults(func=cmd_exports)

    w = sub.add_parser("write-cockpit", help="write cockpit/.env from root .env")
    w.add_argument("repo_root")
    w.add_argument("env_file")
    w.add_argument("out_env")
    w.add_argument("base_url")
    w.set_defaults(func=cmd_write_cockpit)

    h = sub.add_parser("hub-x-key", help="first hub key value for curl (stdout)")
    h.add_argument("repo_root")
    h.add_argument("env_file")
    h.set_defaults(func=cmd_hub_x_key)

    args = p.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
